package ca.jonathanfritz.ofxcat.service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Report generated by TokenMigrationService tracking the results of migrating
 * existing transactions to have tokens and applying keyword rules.
 */
public class MigrationReport {

    private int processedCount;
    private int recategorizedCount;
    private int skippedCount;
    private final List<RecategorizationEntry> recategorizations;

    public MigrationReport() {
        this.processedCount = 0;
        this.recategorizedCount = 0;
        this.skippedCount = 0;
        this.recategorizations = new ArrayList<>();
    }

    public void incrementProcessed() {
        processedCount++;
    }

    public void incrementSkipped() {
        skippedCount++;
    }

    public void addRecategorization(String description, String oldCategory, String newCategory) {
        recategorizations.add(new RecategorizationEntry(description, oldCategory, newCategory));
        recategorizedCount++;
    }

    public int getProcessedCount() {
        return processedCount;
    }

    public int getRecategorizedCount() {
        return recategorizedCount;
    }

    public int getSkippedCount() {
        return skippedCount;
    }

    public List<RecategorizationEntry> getRecategorizations() {
        return Collections.unmodifiableList(recategorizations);
    }

    public boolean hasRecategorizations() {
        return !recategorizations.isEmpty();
    }

    /**
     * Record of a single recategorization that occurred during migration.
     */
    public record RecategorizationEntry(String description, String oldCategory, String newCategory) {}

    @Override
    public String toString() {
        return String.format(
                "MigrationReport{processed=%d, recategorized=%d, skipped=%d}",
                processedCount, recategorizedCount, skippedCount);
    }
}
